/**
 * Featured Creations — From the Studio
 * Curated seed content so Explore never shows an empty gallery.
 * Replace URLs with your team’s best AI images when ready.
 */

export type FeaturedSeedItem = {
  id: string;
  prompt: string;
  mode: string;
  url: string;
  thumbnailUrl?: string;
  category: string | null;
  style: string | null;
  likesCount: number;
  commentsCount: number;
  publishedAt: string | null;
  user: { id: string; name: string; profileImageUrl?: string | null } | null;
};

export const FEATURED_SEED_LABEL = "✨ Featured Creations — From the Studio";

export const FEATURED_SEED: FeaturedSeedItem[] = [
  {
    id: "seed-1",
    prompt: "Cyberpunk portrait, neon lights, rain-soaked street, cinematic lighting",
    mode: "creative",
    url: "https://picsum.photos/seed/explore1/800/1000",
    category: "Portrait",
    style: "Cinematic",
    likesCount: 124,
    commentsCount: 8,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-2",
    prompt: "Studio portrait, soft diffused light, neutral background, professional",
    mode: "portrait",
    url: "https://picsum.photos/seed/explore2/800/1200",
    category: "Portrait",
    style: "Realistic",
    likesCount: 89,
    commentsCount: 3,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-3",
    prompt: "Dramatic mountain landscape at golden hour, volumetric light",
    mode: "creative",
    url: "https://picsum.photos/seed/explore3/1200/800",
    category: "Scene",
    style: "Cinematic",
    likesCount: 256,
    commentsCount: 12,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-4",
    prompt: "Anime style character, cherry blossoms, soft pastel colors",
    mode: "creative",
    url: "https://picsum.photos/seed/explore4/800/1000",
    category: "Portrait",
    style: "Anime",
    likesCount: 312,
    commentsCount: 19,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-5",
    prompt: "Film noir detective, black and white, high contrast shadows",
    mode: "creative",
    url: "https://picsum.photos/seed/explore5/800/1000",
    category: "Portrait",
    style: "Cinematic",
    likesCount: 167,
    commentsCount: 5,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-6",
    prompt: "Futuristic city skyline at night, flying vehicles, holographic ads",
    mode: "creative",
    url: "https://picsum.photos/seed/explore6/1200/700",
    category: "Scene",
    style: "Cinematic",
    likesCount: 445,
    commentsCount: 22,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-7",
    prompt: "Soft natural light portrait, outdoor, bokeh background",
    mode: "portrait",
    url: "https://picsum.photos/seed/explore7/800/1000",
    category: "Portrait",
    style: "Realistic",
    likesCount: 98,
    commentsCount: 4,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-8",
    prompt: "Fantasy warrior, armor, magical glow, epic composition",
    mode: "creative",
    url: "https://picsum.photos/seed/explore8/800/1100",
    category: "Portrait",
    style: "Cinematic",
    likesCount: 278,
    commentsCount: 14,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-9",
    prompt: "Minimalist interior, Scandinavian design, morning light",
    mode: "creative",
    url: "https://picsum.photos/seed/explore9/1200/800",
    category: "Scene",
    style: "Realistic",
    likesCount: 134,
    commentsCount: 6,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-10",
    prompt: "Vintage film look, 1970s fashion, warm tones, grain",
    mode: "creative",
    url: "https://picsum.photos/seed/explore10/800/1000",
    category: "Portrait",
    style: "Cinematic",
    likesCount: 201,
    commentsCount: 9,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-11",
    prompt: "Underwater scene, rays of light, peaceful, blue tones",
    mode: "creative",
    url: "https://picsum.photos/seed/explore11/1000/800",
    category: "Scene",
    style: "Realistic",
    likesCount: 189,
    commentsCount: 7,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-12",
    prompt: "Fashion editorial, dramatic makeup, studio lighting",
    mode: "portrait",
    url: "https://picsum.photos/seed/explore12/800/1200",
    category: "Portrait",
    style: "Realistic",
    likesCount: 156,
    commentsCount: 11,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-13",
    prompt: "Space station above Earth, astronauts, Earth glow",
    mode: "creative",
    url: "https://picsum.photos/seed/explore13/1200/800",
    category: "Scene",
    style: "Cinematic",
    likesCount: 523,
    commentsCount: 28,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-14",
    prompt: "Cozy coffee shop, rainy window, warm interior lights",
    mode: "creative",
    url: "https://picsum.photos/seed/explore14/1000/800",
    category: "Scene",
    style: "Realistic",
    likesCount: 267,
    commentsCount: 15,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-15",
    prompt: "Samurai in snow, cherry blossom petals, calm intensity",
    mode: "creative",
    url: "https://picsum.photos/seed/explore15/800/1000",
    category: "Portrait",
    style: "Cinematic",
    likesCount: 392,
    commentsCount: 18,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-16",
    prompt: "Abstract fluid art, vibrant colors, motion blur",
    mode: "creative",
    url: "https://picsum.photos/seed/explore16/800/800",
    category: "Scene",
    style: "Abstract",
    likesCount: 145,
    commentsCount: 2,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-17",
    prompt: "Golden hour wedding portrait, field of flowers, soft focus",
    mode: "portrait",
    url: "https://picsum.photos/seed/explore17/800/1000",
    category: "Portrait",
    style: "Realistic",
    likesCount: 221,
    commentsCount: 13,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-18",
    prompt: "Post-apocalyptic city, overgrown, sunset, hopeful",
    mode: "creative",
    url: "https://picsum.photos/seed/explore18/1200/700",
    category: "Scene",
    style: "Cinematic",
    likesCount: 334,
    commentsCount: 20,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-19",
    prompt: "Close-up portrait, rim light, dark background, intense eyes",
    mode: "portrait",
    url: "https://picsum.photos/seed/explore19/800/1000",
    category: "Portrait",
    style: "Realistic",
    likesCount: 178,
    commentsCount: 8,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-20",
    prompt: "Steampunk inventor, brass gears, workshop, warm light",
    mode: "creative",
    url: "https://picsum.photos/seed/explore20/800/1000",
    category: "Portrait",
    style: "Cinematic",
    likesCount: 289,
    commentsCount: 16,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-21",
    prompt: "Nordic fjord, mist, mountains, mirror water",
    mode: "creative",
    url: "https://picsum.photos/seed/explore21/1200/800",
    category: "Scene",
    style: "Realistic",
    likesCount: 412,
    commentsCount: 24,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-22",
    prompt: "Retro sci-fi book cover, spaceship, planet, vintage colors",
    mode: "creative",
    url: "https://picsum.photos/seed/explore22/800/1100",
    category: "Scene",
    style: "Cinematic",
    likesCount: 198,
    commentsCount: 5,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-23",
    prompt: "Professional headshot, corporate, clean background",
    mode: "portrait",
    url: "https://picsum.photos/seed/explore23/800/1000",
    category: "Portrait",
    style: "Realistic",
    likesCount: 67,
    commentsCount: 1,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-24",
    prompt: "Magical forest, bioluminescent plants, fairy tale mood",
    mode: "creative",
    url: "https://picsum.photos/seed/explore24/1200/800",
    category: "Scene",
    style: "Cinematic",
    likesCount: 376,
    commentsCount: 21,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
  {
    id: "seed-25",
    prompt: "Street photography, urban, candid, golden hour",
    mode: "creative",
    url: "https://picsum.photos/seed/explore25/800/1000",
    category: "Scene",
    style: "Realistic",
    likesCount: 143,
    commentsCount: 6,
    publishedAt: null,
    user: { id: "studio", name: "PhotoGenius Studio", profileImageUrl: null },
  },
];
